# Generated by Django 2.2.5 on 2019-11-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(db_index=True, max_length=100, verbose_name='День недели')),
                ('lesson1', models.CharField(db_index=True, max_length=100, verbose_name='Урок 1')),
                ('lesson2', models.CharField(db_index=True, max_length=100, verbose_name='Урок 2')),
                ('lesson3', models.CharField(db_index=True, max_length=100, verbose_name='Урок 3')),
                ('lesson4', models.CharField(db_index=True, max_length=100, verbose_name='Урок 4')),
                ('lesson5', models.CharField(db_index=True, max_length=100, verbose_name='Урок 5')),
                ('lesson6', models.CharField(db_index=True, max_length=100, verbose_name='Урок 6')),
                ('lesson7', models.CharField(db_index=True, max_length=100, verbose_name='Урок 7')),
            ],
            options={
                'verbose_name': 'Расписание',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(db_index=True, verbose_name='Содержание новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Заголовок новости'),
        ),
    ]
